spring:
  application:
    name: api-gateway-be
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8083/realms/main}
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: MetaData-SERVICE
              uri: http://localhost:8081
              predicates:
                - Path=/api/metadata/**
server:
  port: 8087

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.servlet.function: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

# Swagger-driven authorization â€” downstream service spec URLs
gateway:
  authz:
    specs:
      metadata-service: http://localhost:8081/v3/api-docs
    refresh-interval-ms: 300000  # refresh specs every 5 min
